version: '2'
services:
  rss-bridge:
    container_name: rss-bridge
    volumes:
      - ./whitelist.txt:/app/whitelist.txt
    build:
      context: .
    image: rssbridge/rss-bridge:latest
    ports:
      - 29300:80