version: '2'
services:
  rss-bridge:
    container_name: rss-bridge
    volumes:
      - /home/ccllssd/webservice/rssreader/rss-bridge/whitelist.txt:/app/whitelist.txt
    build:
      context: .
    image: rssbridge/rss-bridge:latest
networks:
  default:
    external:
      name: nginx-proxy
