version: "3.8"
services:
  webdav:
    container_name: webdav
    image: bytemark/webdav
    volumes:
      - /home/ccllssd/webfile/webdav/user.passwd:/user.passwd
      - cloudbox:/var/lib/dav/data/cloudbox
      - pdfs:/var/lib/dav/data/pdfs
      - bgmi_bangumi:/var/lib/dav/data/bgmi_bangumi
      - aria2_downloads:/var/lib/dav/data/aria2_downloads
      - smallshare:/var/lib/dav/data/smallshare
      - mousou:/var/lib/dav/data/mousou
    # ports:
    #   - 29180:80
    #   - 29184:443
    networks:
      - nginx-proxy
      - caddy-net
    restart: always
volumes:
  cloudbox:
    external: true
  pdfs:
    external: true
  bgmi_bangumi:
    external: true
  aria2_downloads:
    external: true
  smallshare:
    external: true
  mousou:
    external: true
networks:
  nginx-proxy:
    external: 
      name: nginx-proxy
  caddy-net:
    external: 
      name: caddy-net