version: "3.4"

services:
  app:
    container_name: monica_app
    build: ./app
    depends_on:
      - db
    env_file: .env
    volumes:
      - monica_data:/var/www/html/storage
    restart: always

  web:
    container_name: monica_web
    build: ./web
    restart: always
    ports:
      - 29780:80
    volumes:
      - monica_data:/var/www/html/storage:ro
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: monica_db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=a780c53f7722c8
    volumes:
      - monica_mysql:/var/lib/mysql
    restart: always

volumes:
  monica_data:
  monica_mysql:

