---
version: '3'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    container_name: umami
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: ccll
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    container_name: umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
volumes:
  umami-db-data:
networks:
  default:
    external:
      name: nginx-proxy
